# Generated by Django 2.1.4 on 2018-12-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_instansi', models.CharField(max_length=255)),
                ('kategori', models.CharField(choices=[('swasta', 'Swasta'), ('pemerintah', 'Pemerintah')], max_length=255)),
                ('telepon', models.CharField(blank=True, max_length=255, null=True)),
                ('kode_pos', models.CharField(blank=True, max_length=255, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(max_length=255)),
                ('tgl_surat', models.CharField(help_text='Tanggal di dalam isi surat', max_length=255, verbose_name='Tanggal surat')),
                ('perihal', models.CharField(max_length=255)),
                ('pengirim', models.CharField(blank=True, help_text='Orang atau jasa yang mengantar surat', max_length=255, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuratKeluar',
            fields=[
                ('surat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surat_menyurat.Surat')),
                ('tgl_keluar', models.CharField(help_text='Tanggal keluar surat dari kantor', max_length=255, verbose_name='Tanggal keluar')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('tujuan_instansi', models.ForeignKey(help_text='Jika tujuan instansi tidak ada, silahkan ke menu instansi', on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.Instansi')),
            ],
            bases=('surat_menyurat.surat',),
        ),
        migrations.CreateModel(
            name='SuratMasuk',
            fields=[
                ('surat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='surat_menyurat.Surat')),
                ('tgl_masuk', models.CharField(help_text='Tanggal masuk surat ke kantor', max_length=255, verbose_name='Tanggal masuk')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asal_instansi', models.ForeignKey(help_text='Jika asal instansi tidak ada, silahkan ke menu instansi', on_delete=django.db.models.deletion.CASCADE, to='surat_menyurat.Instansi')),
            ],
            bases=('surat_menyurat.surat',),
        ),
    ]
